import type { Property } from "../auth-types/property.types";

export interface Agent {
    id: string;
    name: string;
    role: string;
    specialty: string;
    experience: string;
    phone: string;
    email: string;
    image: string;
    rating: number;
    reviews: number;
}

export const PLACEHOLDER_PROPERTIES: Property[] = [
    {
        id: 1,
        title: "Modern Luxury Villa",
        description: "A beautiful modern villa with all amenities.",
        price: 1250000,
        location: "Kapan, Kathmandu",
        propertyType: "HOUSE",
        listingType: "SALE",
        bedrooms: 5,
        bathrooms: 4,
        areaSqFt: 3200,
        images: ["https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&q=80&w=800"],
        landlordId: 101,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: 2,
        title: "Charming Apartment in Lazimpat",
        description: "Fully furnished apartment in a quiet neighborhood.",
        price: 45000,
        location: "Lazimpat, Kathmandu",
        propertyType: "APARTMENT",
        listingType: "RENT",
        bedrooms: 2,
        bathrooms: 2,
        areaSqFt: 1200,
        images: ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=800"],
        landlordId: 101,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: 3,
        title: "Spacious Family Home",
        description: "Large backyard and modern kitchen.",
        price: 850000,
        location: "Baneshwor, Kathmandu",
        propertyType: "HOUSE",
        listingType: "SALE",
        bedrooms: 4,
        bathrooms: 3,
        areaSqFt: 2500,
        images: ["https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&q=80&w=800"],
        landlordId: 102,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: 4,
        title: "Modern Studio",
        description: "Compact and efficient living space.",
        price: 25000,
        location: "Jhamsikhel, Lalitpur",
        propertyType: "APARTMENT",
        listingType: "RENT",
        bedrooms: 1,
        bathrooms: 1,
        areaSqFt: 600,
        images: ["https://images.unsplash.com/photo-1536376074432-bf121770998a?auto=format&fit=crop&q=80&w=800"],
        landlordId: 103,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: 5,
        title: "Newly Built Commercial Space",
        description: "Perfect for offices or retail.",
        price: 150000,
        location: "Durbar Marg, Kathmandu",
        propertyType: "COMMERCIAL",
        listingType: "RENT",
        bedrooms: 0,
        bathrooms: 2,
        areaSqFt: 1500,
        images: ["https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=800"],
        landlordId: 104,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: 6,
        title: "Prime Land for Sale",
        description: "Great investment opportunity.",
        price: 5000000,
        location: "Budhanilkantha, Kathmandu",
        propertyType: "LAND",
        listingType: "SALE",
        bedrooms: 0,
        bathrooms: 0,
        areaSqFt: 5400,
        images: ["https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&q=80&w=800"],
        landlordId: 105,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    }
];

export const PLACEHOLDER_AGENTS: Agent[] = [
    {
        id: "a1",
        name: "Suman Sharma",
        role: "Senior Real Estate Consultant",
        specialty: "Luxury Homes & Villas",
        experience: "10+ years",
        phone: "+977 9801234567",
        email: "suman@hamrorealstate.com",
        image: "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&q=80&w=400",
        rating: 4.9,
        reviews: 124,
    },
    {
        id: "a2",
        name: "Pooja Karki",
        role: "Residential Property Specialist",
        specialty: "Apartments & Rentals",
        experience: "6 years",
        phone: "+977 9812345678",
        email: "pooja@hamrorealstate.com",
        image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=400",
        rating: 4.8,
        reviews: 89,
    },
    {
        id: "a3",
        name: "Rahul Thapa",
        role: "Commercial Real Estate Expert",
        specialty: "Retail & Office Spaces",
        experience: "8 years",
        phone: "+977 9845678901",
        email: "rahul@hamrorealstate.com",
        image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=400",
        rating: 4.7,
        reviews: 56,
    },
    {
        id: "a4",
        name: "Anjali Gurung",
        role: "New Construction Advisor",
        specialty: "Developers & New Launches",
        experience: "5 years",
        phone: "+977 9856789012",
        email: "anjali@hamrorealstate.com",
        image: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=400",
        rating: 4.9,
        reviews: 72,
    }
];
